# Generated by Django 5.0.1 on 2024-02-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_category_alter_contact_picture_contact_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
